repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/myint/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
        args:
          - "--remove-all-unused-imports"
          - "--in-place"
          - "--ignore-init-module-imports"
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.253
    hooks:
      - id: ruff
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint
        args: [--ignore, DL3007, --ignore, DL3008, --ignore, DL3015]
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
default_language_version:
  python: python3.11
exclude: ^(scripts|tests)
