version: "3.9"
services:
  devinteract-api:
    build:
      context: .
    container_name: some-api
    command: "gunicorn app.main:app --bind 0.0.0.0:4000 --reuse-port -k app.core.CustomUvicornWorker"
    ports:
      - "4000:4000"
