[tool.poetry]
name = "{{ cookiecutter.project_name }}"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [
    { include = "app" },
]


[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.85.2"
uvicorn = "^0.19.0"
gunicorn = "^20.1.0"


[tool.poetry.dev-dependencies]
autoflake = "^1.7.7"
black = "^22.10.0"
isort = "^5.10.1"
mypy = "^0.982"
flake8 = "^5.0.4"
flake8-bugbear = "^22.10.27"
flake8-simplify = "^0.19.3"
flake8-class-attributes-order = "^0.1.3"
flake8-comprehensions = "^3.10.1"
flake8-use-fstring = "^1.4"
flake8-functions-names = "^0.3.0"
pep8-naming = "^0.13.2"
yesqa = "^1.4.0"
flake8-absolute-import = "^1.0.0"
flake8-implicit-str-concat = "^0.3.0"
flake8-black = "^0.3.3"
flake8-isort = "^5.0.0"


[tool.black]
line-length = 88
target-version = ['py310']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
python_version = "3.10"
warn_no_return = true
warn_unreachable = true
warn_incomplete_stub = true
warn_unused_configs = true

[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
skip_gitignore = true
extra_standard_library = ["typing_extensions"]
skip = []
